class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://github.com/astral-sh/uv"
  url "https://mirror.ghproxy.com/https://github.com/astral-sh/uv/archive/refs/tags/0.2.22.tar.gz"
  sha256 "982373b72bf7841a5f31a5b2f19e027d70a14c201434bf427dc76a5bbfcc0d8b"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "55d6aab11e026a54d52a4edd3e6a83dcaddef553cc816fb55a7acb56a24599d2"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "5d3601e8bc667a622e43d13d216b6586e5010910295de2022b1bd1e0f6b7dfa8"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "aeaffbb6f1fa5a86293cae2e0f35f4513756905555dffdeb442eef49b8568e96"
    sha256 cellar: :any_skip_relocation, sonoma:         "73e7e21367756be03af88ea41b3ce0345c61bcc1599ef498cc94062be73fd2a5"
    sha256 cellar: :any_skip_relocation, ventura:        "5d2393a70d3ab12b4a59c9ccd505f7dfda7011448234676189df339ac695e8b3"
    sha256 cellar: :any_skip_relocation, monterey:       "f4bd29c6d72403b36bc746c92e10c336d6cb0603a17a968b54bf76ef0dc8eafb"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "47dff1adc1ea3a07e78858a5558f881a149b5df1460c28012875203daf6accda"
  end

  depends_on "pkg-config" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test

  on_linux do
    # On macOS, bzip2-sys will use the bundled lib as it cannot find the system or brew lib.
    # We only ship bzip2.pc on Linux which bzip2-sys needs to find library.
    depends_on "bzip2"
  end

  def install
    system "cargo", "install", "--no-default-features", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~EOS
      requests
    EOS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled
  end
end
