class Sqlc < Formula
  desc "Generate type safe Go from SQL"
  homepage "https://sqlc.dev/"
  url "https://github.com/kyleconroy/sqlc/archive/v1.16.0.tar.gz"
  sha256 "40edb0cee447d8947e5d515c65ba75157dbc5dab057691b11b5957c6c7dd1519"
  license "MIT"
  head "https://github.com/kyleconroy/sqlc.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_monterey: "a4170e863839e2931b98a762557003afeaf2bd36e07e7b0f6aa6cb1676e6a945"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "c4115cf0c9ca5468148765fc9b453c1172981a9f2031a59f966fed473f017988"
    sha256 cellar: :any_skip_relocation, ventura:        "26317447465dfadc090b44539e5c0ecc4a833d55bb537a6816a3b07ded05e1d3"
    sha256 cellar: :any_skip_relocation, monterey:       "2010f5477aaf1076d49cc51a0b837b8779183cd8c8a67c42f117c65fc439a71a"
    sha256 cellar: :any_skip_relocation, big_sur:        "b50a4d988e27ea54542a1abda3e7efb611f5b4fef9eaab52519e14f6553e075f"
    sha256 cellar: :any_skip_relocation, catalina:       "adcd071ce6993f4758010eefe731d2ab7af4ea946da04e8fd89c2834fde89a0e"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "885e9c12496b92bb1a2e26f7f4a3339582341783edd30765be43ff3b4e059c5e"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args, "-ldflags", "-s -w", "./cmd/sqlc"
  end

  test do
    (testpath/"sqlc.json").write <<~SQLC
      {
        "version": "1",
        "packages": [
          {
            "name": "db",
            "path": ".",
            "queries": "query.sql",
            "schema": "query.sql",
            "engine": "postgresql"
          }
        ]
      }
    SQLC

    (testpath/"query.sql").write <<~EOS
      CREATE TABLE foo (bar text);

      -- name: SelectFoo :many
      SELECT * FROM foo;
    EOS

    system bin/"sqlc", "generate"
    assert_predicate testpath/"db.go", :exist?
    assert_predicate testpath/"models.go", :exist?
    assert_match "// Code generated by sqlc. DO NOT EDIT.", File.read(testpath/"query.sql.go")
  end
end
