class Libsecret < Formula
  desc "Library for storing/retrieving passwords and other secrets"
  homepage "https://wiki.gnome.org/Projects/Libsecret"
  url "https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.5.tar.xz"
  sha256 "08f45c44760ab4c2d6febd6e0eeb421663b29a72be52c48c61c507b0ef6a7920"
  license all_of: ["LGPL-2.1-or-later", "GPL-2.0-or-later", "Apache-2.0"]

  # libsecret doesn't use GNOME's "even-numbered minor is stable" version
  # scheme. This regex is the same as the one generated by the `Gnome` strategy
  # but it's necessary to avoid the related version scheme logic.
  livecheck do
    url :stable
    regex(/libsecret[._-]v?(\d+(?:\.\d+)+)\.t/i)
  end

  bottle do
    sha256 cellar: :any, arm64_sequoia: "20408875ea75e702404654363420d888a02ced7b35b97f295e3bbc16cb9f9331"
    sha256 cellar: :any, arm64_sonoma:  "bf819debe42b4c9833abca12e326dfc5721f0b7f3d69ee462ef209227801d9db"
    sha256 cellar: :any, arm64_ventura: "c4ed62702f6b6c68a506dc35eda900f79f5793df4acfb174683233204aae1d00"
    sha256 cellar: :any, sonoma:        "1567164ecb7cdd573805fc2a0eeae0b6642a77e5ff75dcb9e102144c8b4c5038"
    sha256 cellar: :any, ventura:       "43621d72968c730e00632615bab4a5bc4fa951507149f6c1ae9cd28ae3139b84"
    sha256               x86_64_linux:  "03ab09b840c2b20e9ad207f8408bab5ca79d0c33852d9fd054e8e448ca0ad617"
  end

  depends_on "docbook-xsl" => :build
  depends_on "gettext" => :build
  depends_on "gobject-introspection" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "pkgconf" => [:build, :test]
  depends_on "vala" => :build
  depends_on "glib"
  depends_on "libgcrypt"
  uses_from_macos "libxslt" => :build

  on_macos do
    depends_on "gettext"
  end

  # ignore dbus test for macos build, upstream pr ref, https://gitlab.gnome.org/GNOME/libsecret/-/merge_requests/156
  patch do
    url "https://gitlab.gnome.org/GNOME/libsecret/-/commit/952caf24867b80b65935f856fb8fb4f96d93c43c.diff"
    sha256 "a175d262c887961bd380130c8354a4d2919027b592a7949d8e94773e46683e0f"
  end

  def install
    ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"

    system "meson", "setup", "build", "-Dbashcompdir=#{bash_completion}",
                                      "-Dgtk_doc=false",
                                      *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
  end

  test do
    (testpath/"test.c").write <<~C
      #include <libsecret/secret.h>

      const SecretSchema * example_get_schema (void) G_GNUC_CONST;

      const SecretSchema *
      example_get_schema (void)
      {
          static const SecretSchema the_schema = {
              "org.example.Password", SECRET_SCHEMA_NONE,
              {
                  {  "number", SECRET_SCHEMA_ATTRIBUTE_INTEGER },
                  {  "string", SECRET_SCHEMA_ATTRIBUTE_STRING },
                  {  "even", SECRET_SCHEMA_ATTRIBUTE_BOOLEAN },
                  {  "NULL", 0 },
              }
          };
          return &the_schema;
      }

      int main()
      {
          example_get_schema();
          return 0;
      }
    C

    flags = shell_output("pkgconf --cflags --libs libsecret-1").chomp.split
    system ENV.cc, "test.c", "-o", "test", *flags
    system "./test"
  end
end
