on:
  push:
    branches:    
      - 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions/checkout@v3
      with:
        repository: 'Homebrew/homebrew-core'
        fetch-depth: 1
        path: 'homebrew-core'
    - uses: actions/checkout@v3
      with:
        repository: 'Homebrew/homebrew-cask'
        fetch-depth: 1
        path: 'homebrew-cask'
    - name: Update buckets
      run: |
        bash ./update.sh
        echo "Updated on $(date)" >log
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git commit -am "Updated on $(date)"
        git push -f origin main
